steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-west1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/jitaccess:latest', '.' ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-west1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/jitaccess:latest' ]