steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - |
        cd ${_DOCKERFILE_PATH} &&
        docker build \
          -t us-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG} \
          -f ${_DOCKERFILE_PATH}/Dockerfile .

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}' ]
